### ISSUE TITLE
Hamburger menu icon is not displayed

### ISSUE THREAD

**Issue by ondrejbasegit** [themefisher/bigspring-hugo-startup-theme#17]
Even in the live demo: https://themes.gohugo.io/theme/bigspring-hugo-startup-theme/

When you change the size of the window to the mobile breakpoint, the empty box (or question mark on actual mobile web browser) is displayed instead of the **ti-menu** icon.

**Comment by ondrejbasegit** [comment]
Fixed manually by changing the:
`<i class="ti-menu h3"></i>`
in the **header.html** file to:
`<i class="ti-menu"></i>`

**Comment by developer-evan** [comment]
@ondrejbasegit 

Thanks for your concern. I updated this.

**Comment by fgenoese** [comment]
I noted that this fix is not working properly with the latest version from the git repo. 
Same behaviour on the gohugo.io demo page: https://themes.gohugo.io/theme/bigspring-hugo-startup-theme/
Same behaviour on the page deployed on Netlify, as reported in issue https://github.com/themefisher/bigspring-hugo-startup-theme/issues/29#issuecomment-805454887

**However**, on the following demo page I can see the hamburger menu (despite the fact that it contains the h3 attribute):
https://demo.themefisher.com/bigspring-hugo/

**Comment by somratpro** [comment]
@fgenoese 

Thanks for your concern, this issue has been fixed. download the latest code.

**Comment by fgenoese** [comment]
The issue is still there with the latest code. 

https://bigspring-test.netlify.app/

**Comment by somratpro** [comment]
![Screenshot_20210328-113113](https://user-images.githubusercontent.com/37659754/112743446-32447100-8fb9-11eb-86a0-e4bb664a3e8f.jpg)
check it out

**Comment by fgenoese** [comment]
Working now with your latest commit from a few hours ago. https://github.com/themefisher/bigspring-hugo-startup-theme/commit/8674826b88aad97ccb3cd9f5c6813ea70038fc44

Thanks for the quick fix!
![B9CC93C2-F948-43B4-8A66-024BC99BF877](https://user-images.githubusercontent.com/6893619/112762365-925e0600-8fff-11eb-9e61-f2ea60df9378.png)
