### ISSUE TITLE
Generated site is extremely sluggish and menu list bug on mobile view.

### ISSUE THREAD

**Issue by arnaugamez** [themefisher/bigspring-hugo-startup-theme#33]
I have been trying this theme, both locally but also the demo site provided by gohugo (https://themes.gohugo.io//theme/bigspring-hugo-startup-theme/) as the one linked in this repository returns a 404 (https://demo.themefisher.com/bigspring-hugo/). The design is really nice, but the site is so sluggish to the point it is unusable. I first thought I was having problems with my internet connection, but that is not the case. Indeed I reproduced it simply by building the exampleSite locally.

Moving from one page to another takes several seconds, sometimes on the order of tens of seconds. It really feels as it is getting frozen every time an action is performed. I guess there might be some stuff fundamentally broken in the way it is rendering each thing, or maybe heavy remote assets loaded every time. Indeed, when trying to navigate through it, even Firefox displays me the yellow warning banner with message "A website is slowing down your browser. Stop it or wait?".

Another thing I noticed is that the menu button on mobile version (the three lines to show menu) has a bug that it dos not collapse once it has been expanded once. Whenever you click again on it (and after waiting, again, several seconds) if it was already expanded, it just flashes expanding again, not collapsing.

I am not familiar with hugo themes internals, but if there is any more information you would like me to provide, just let me know.

**Comment by somratpro** [comment]
Hello @arnaugamez 

Thanks for your concern. We have fixed this issue. you can download the latest code from GitHub and enjoy it.

Also If you like our theme, a star to the repository would be charming.

**Comment by arnaugamez** [comment]
Thanks, moving better now. Though, the bug in menu button on mobile is still not solved, it still does not collapse once it has been expanded.

**Comment by GaranceR** [comment]
@somratpro Could you guys also fix the menu button not collapsing when we click on it? (responsive version) I also have that problem
Thanks!!

**Comment by somratpro** [comment]
Hello all,

I actually could not found why this is happening. so I could not fix it. I have tried many things, but no luck. If anyone found why this is happening, then consider letting me know. I'll fix it ASAP

**Comment by somratpro** [comment]
Hello there, 

This issue has been fixed. please download the latest code. thank you
